model_kwargs:
  model: Qwen/Qwen3-4B-Instruct-2507
  dtype: bfloat16
  quantization: mxfp4 # bitsandbytes
  seed: 42
generation_args:
  sampling_params:
    n: 1
    max_tokens: 16384
    seed: 42
    temperature: 0.7
online_args:
  client_params:
    base_url: http://localhost
    port: 8000
  common_params:
    model: openai/gpt-oss-120b
    max_output_tokens: 16384
    temperature: 0.7
    timeout: 180
    reasoning:
      effort: default
evaluation_args:
  client_params:
    base_url: http://localhost
    port: 8000
  common_params:
    model: openai/gpt-oss-120b
    max_output_tokens: 16384
    temperature: 0.7
    timeout: 180
    reasoning:
      effort: high
