[project]
name = "agentic-memory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.11.0",
    "torchaudio>=2.11.0",
    "torchvision>=0.26.0",
    "transformers>=5.13.1",
    "vllm>=0.20.0",
]

[[tool.uv.index]]
name = "flashinfer-cuda"
url = "https://flashinfer.ai/whl/cu130"
explicit = true

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cuda"},
]
torchvision = [
  { index = "pytorch-cuda"},
]
torchaudio = [
  { index = "pytorch-cuda"},
]
torchao = [
  { index = "pytorch-cuda"},
]
flashinfer-jit-cache = [
    { index = "pytorch-cuda" },
]

xielu = { git = "https://github.com/rubber-duck-debug/xielu.git" }

[tool.uv]
exclude-dependencies = ['pynvml']

[tool.uv.extra-build-dependencies]
flash-attn = ["torch"]
xielu = ["torch"]